#!/usr/bin/env bash
set -e

NETWORK=seroviz_nw
TAG=seroanalytics/seroviz:main
API_TAG=seroanalytics/serovizr:main

function cleanupDocker() {
  docker kill seroviz > /dev/null 2>&1 || true
  docker kill serovizr > /dev/null 2>&1 || true
  docker rm seroviz > /dev/null 2>&1 || true
  docker rm serovizr > /dev/null 2>&1 || true
  docker network rm $NETWORK > /dev/null 2>&1 || true
}

trap cleanup ERR
trap cleanup EXIT
function cleanup() {
  hcp auth logout
  cleanupDocker
}

if [[ ! -v "CLIENT_ID" ]]; then
    echo Please provide production client id from Vault.
    echo -e To read this from Vault on another machine, run:
    echo ""
    echo -e "\t hcp vs secrets open production_id --app=seroviz"
    echo ""
    read -r CLIENT_ID
fi

if [[ ! -v "CLIENT_SECRET" ]]; then
    echo Please provide production client secret from Vault
    echo -e To read this from Vault on another machine, run:
    echo ""
    echo -e "\t hcp vs secrets open production_secret --app=seroviz"
    echo ""
    read -r CLIENT_SECRET
fi

hcp auth login --client-id="$CLIENT_ID" --client-secret="$CLIENT_SECRET"

NETWORK=seroviz_nw
TAG=seroanalytics/seroviz:main
API_TAG=seroanalytics/serovizr:main

docker pull $TAG
docker pull $API_TAG

docker network create $NETWORK

docker run -d -p 8888:8888 --network=$NETWORK --name serovizr $API_TAG
docker run -d -p 80:80 -p 443:443 --network=$NETWORK --name seroviz $TAG seroviz.seroanalytics.org

TEMP_KEY=$(mktemp -q)
hcp vs secrets open ssl_key --app seroviz --out-file=$TEMP_KEY
docker cp $TEMP_KEY seroviz:/run/proxy/key.pem

TEMP_INT_1=$(mktemp -q)
hcp vs secrets open ssl_intermediate_1 --app seroviz --out-file=$TEMP_INT_1
TEMP_INT_2=$(mktemp -q)
hcp vs secrets open ssl_intermediate_2 --app seroviz --out-file=$TEMP_INT_2
TEMP_INT_3=$(mktemp -q)
hcp vs secrets open ssl_intermediate_3 --app seroviz --out-file=$TEMP_INT_3
TEMP_INT_CERT=$(mktemp -q)
hcp vs secrets open ssl_cert --app seroviz --out-file=$TEMP_INT_CERT

TEMP_BUNDLE=$(mktemp -q)
cat $TEMP_INT_CERT $TEMP_INT_1 $TEMP_INT_2 $TEMP_INT_3 >> $TEMP_BUNDLE
docker cp $TEMP_BUNDLE seroviz:/run/proxy/certificate.pem
